version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      # Cannot use dependency:go-offline due to https://github.com/apache/maven-dependency-plugin/pull/2
      - run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn clean install -pl !dcre2e,!pl.petergood:dcracceptancetestshelpers,!pl.petergood:dcrcompilationworkeracceptancetests,!pl.petergood:dcrlanguageacceptancetests,!pl.petergood:dcrrunnerworkercoreacceptancetests,!pl.petergood:dcrshellacceptancetests,!pl.petergood:dcrsimplerunnerworkeracceptancetests,!pl.petergood:dcrcompilationworkere2e,!pl.petergood:dcrsimplerunnerworkere2e,!pl.petergood:fulle2e