version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_CREATE_TOPICS: "processing-request:1:1,processing-result:1:1,processing-failure:1:1,simple-execution-request:1:1,simple-execution-result:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  compilationworker:
    image: dcrcompilationworker:latest
    privileged: true
    environment:
      DCR_COMPILATIONWORKER_JAIL_CONFIGURATION_KAFKA_BOOTSTRAP_URLS: "kafka:9092"
  simplerunnerworker:
    image: dcrsimplerunnerworker:latest
    privileged: true
    environment:
      DCR_SIMPLERUNNERWORKER_BROKER_BOOTSTRAP_URLS: "kafka:9092"
      DCR_SIMPLERUNNERWORKER_CONFIGURATIONSERVICE_URL: "http://configurationservice:8080"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: hello
      POSTGRES_DB: configurationservice
  configurationservice:
    image: dcrconfigurationservice:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/configurationservice
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: hello
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
    ports:
      - "8080:8080"