apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-single
  namespace: kafka-cluster
spec:
  selector:
    matchLabels:
      app: kafka-single
  serviceName: kafka-single
  template:
    metadata:
      labels:
        app: kafka-single
    spec:
      containers:
        - image: wurstmeister/kafka
          name: kafka
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: 'zookeeper-single:2181'
            - name: KAFKA_LISTENERS
              value: 'INSIDE://kafka-single:9092,OUTSIDE://kafka-single:9093'
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: 'INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT'
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: 'INSIDE'
          volumeMounts:
            - name: kafka-single-data
              mountPath: '/tmp/kafka-logs'
          ports:
            - containerPort: 9092
  volumeClaimTemplates:
    - metadata:
        name: kafka-single-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-single
  namespace: kafka-cluster
spec:
  ports:
    - port: 9092
      name: inside
    - port: 9093
      name: outside
  clusterIP: None
  selector:
    app: kafka-single