kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: zookeeper-single
  namespace: kafka-cluster
spec:
  serviceName: zookeeper-single
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-single
  template:
    metadata:
      labels:
        app: zookeeper-single
    spec:
      containers:
        - name: zookeeper
          image: zookeeper
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_ID
              value: "1"
            - name: ZOOKEEPER_SERVER_1
              value: zookeeper-single
          volumeMounts:
            - name: zookeeper-single-data
              mountPath: "/data"
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-single-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-single
  namespace: kafka-cluster
  labels:
    app: zookeeper-single
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
  selector:
    app: zookeeper-single
